### ISSUE TITLE
How do I create a TSDF map?

### ISSUE THREAD

**Issue by Taeyoung96** [uos/tsdf_localization#1]
@jspricke @maeisoldt
Thanks for releasing a great project!  
What method did you use to create a TSDF map utilizing the Hilti dataset?  
I'd appreciate it if you could share any code or papers you've used.

Thanks,

**Comment by maeisoldt** [comment]
Thank you for your interest in our work.

We used HATSDF SLAM (https://github.com/uos/hatsdf_slam) to generate the TSDF maps for all experiments. The system is able to process prerecorded bag files. Further information about the implementation and the used platform can be found in https://ieeexplore.ieee.org/document/9568815.

**Comment by Taeyoung96** [comment]
@maeisoldt   
Thanks for your reply!
